import Erdos339

#check Erdos339.erdos_339_upperDensity
#check Erdos339.upperDensity_nsmul_le_restrictedSums
#print axioms Erdos339.erdos_339_upperDensity
#print axioms Erdos339.upperDensity_nsmul_le_restrictedSums
