name = "Erdos339"
version = "0.1.0"
defaultTargets = ["Erdos339"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.1"

[[lean_lib]]
name = "Erdos339"

[[lean_lib]]
name = "Util"
