import Mathlib
#check Nat.le_floor_iff
#check Nat.floor_le
#check Nat.lt_floor_add_one
#check Nat.ceil_le
#check Nat.floor_natCast
#check Real.sqrt_div
#check Filter.limsup_congr
#check Filter.limsup_congr'
#check Filter.EventuallyEq.limsup_eq
#check Filter.limsup_comp
#check Filter.limsup_map
#check Filter.isBoundedUnder_of_eventually_le
#check Filter.isBoundedUnder_of_eventually_ge
#check Real.continuous_sqrt
#check Filter.map_map
#check Filter.EventuallyEq.liminf_eq
#check Filter.liminf_congr'
#check Nat.floor_lt
#check Nat.ceil_pos
#check Filter.Tendsto.limsup_eq
#check Filter.Tendsto.liminf_eq
